apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandwich-facts-deployment
  labels:
    app: sandwich-facts
    owner: andrew
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sandwich-facts
  template:
    metadata:
      labels:
        app: sandwich-facts
    spec:
      containers:
      - name: sandwich-facts
        image: nginx:1.14.2
        ports:
        - containerPort: 8080